package com.cloven.dev.erodev.model.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Builder;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@DynamoDBTable(tableName = "erp_address")
@Builder
@Data
@DynamoDBDocument
public class Address {

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private Integer addressId;

	@DynamoDBAttribute
	private String line1;

	@DynamoDBAttribute
	private String line2;

	@DynamoDBAttribute
	private String city;

	@DynamoDBAttribute
	private String country;

	@DynamoDBAttribute
	private String pinCode;
}
