package com.cloven.dev.erodev.model.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedEnum;
import com.cloven.dev.erpdev.model.utils.AttachmentTypeEnum;

import lombok.Builder;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@DynamoDBTable(tableName = "erp_attachment")
@Builder
@Data
@DynamoDBDocument
public class Attachment {

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String attachmentId;

	@DynamoDBTypeConvertedEnum
	@DynamoDBAttribute(attributeName = "type")
	private AttachmentTypeEnum type;

	@DynamoDBAttribute(attributeName = "uploaded_by")
	private String uploadedUserId;

	@DynamoDBAttribute(attributeName = "user_id")
	private String userId;

	@DynamoDBAttribute(attributeName = "file_path")
	private String filePath;

	@DynamoDBAttribute(attributeName = "original_file_name")
	private String orignalFileName;

	@DynamoDBAttribute(attributeName = "system_file_name")
	private String systemFileName;

	@DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
	private String createdAt;

	@DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
	private String updateAt;

}
