package com.cloven.dev.erodev.model.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedEnum;
import com.cloven.dev.erpdev.model.utils.BatchStatusEnum;

public class Batch {

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private Integer batchId;

	@DynamoDBAttribute(attributeName = "startyear")
	private Integer startyear;

	@DynamoDBAttribute(attributeName = "endyear")
	private Integer endyear;

	@DynamoDBTypeConvertedEnum
	@DynamoDBAttribute(attributeName = "batchstatus")
	private BatchStatusEnum batchStatus;
	
	
	@DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
	private String createdAt;

	@DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
	private String updateAt;
}
