package com.cloven.dev.erodev.model.entity;

import java.io.Serializable;
import java.util.Set;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperFieldModel.DynamoDBAttributeType;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTyped;

import lombok.Builder;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@DynamoDBTable(tableName = "erp_course")
@Builder
@Data
@DynamoDBDocument
public class Course implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5335300202503839508L;

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String courseId;
	
    @DynamoDBAttribute(attributeName = "coursename")
	private String coursename;
	
    @DynamoDBAttribute(attributeName = "coursedescription")
	private String coursedescription;

    @DynamoDBTyped(DynamoDBAttributeType.L)
	private Set<User> students;
    
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
	private String createdAt;

	@DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
	private String updateAt;
}